# Generated by Django 4.1 on 2022-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
