# Generated by Django 4.1 on 2022-08-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
