# Generated by Django 4.0.6 on 2022-08-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
