# Generated by Django 4.1 on 2022-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_case',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
