# Generated by Django 4.1 on 2022-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_patient_patient_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profilepic',
            field=models.ImageField(upload_to='media/patients/4589'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=27, null=True),
        ),
    ]
