# Generated by Django 4.1 on 2022-08-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_active_alter_patient_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profilepic',
            field=models.ImageField(upload_to='media/doctor7537'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profilepic',
            field=models.ImageField(upload_to='media/patients/4698'),
        ),
    ]
