# Generated by Django 4.1 on 2022-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_doctor_profilepic_alter_patient_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profilepic',
            field=models.ImageField(default='media/default.png', upload_to='media/doctor/7708'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profilepic',
            field=models.ImageField(default='media/default.png', upload_to='media/patients/4744'),
        ),
    ]
