# Generated by Django 4.1 on 2022-08-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
