# Generated by Django 4.1 on 2022-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_doctor_experience_remove_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
