# Generated by Django 4.1 on 2022-08-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_options_alter_doctor_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
