# Generated by Django 4.1 on 2022-08-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
